#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
# Madeira Converter Exception: see LICENSE-EXCEPTION.md
#
# mirror_ci.py - write the workflows for the build host repository.
#
# WHY THIS EXISTS
# GitHub has Actions disabled on the sheltonsilas/Madeira fork. Every dispatch
# and every push there is refused with
#
#     {"message": "Actions has been disabled for this repository.", "status": "422"}
#
# and the repository's own Actions permissions endpoint still answers
# {"enabled": true}, so it is not a setting the API can flip. It is not the
# account either: a fresh public repository under the same account dispatches
# and runs normally, which is the test that produced this file.
#
# So builds run in a second, near-empty repository - the build host - and reach
# the real source by name. The build host cannot inherit the fork's caches
# (Actions caches are per-repository, and there is no API to copy one), so the
# host has to warm its own; `llvm-ios` is the expensive one and it is dispatched
# first for that reason.
#
# WHY A GENERATOR AND NOT HAND-WRITTEN COPIES
# A copy that is edited by hand drifts from the original, and the drift shows up
# as a build host that quietly tests something else. This script takes the real
# workflows and makes exactly three changes, each asserted:
#
#   1. `on:` becomes workflow_dispatch only, with a `source_ref` input, because
#      a push to a repository that never contains the source is meaningless.
#   2. Every `actions/checkout` is pinned to the source repository and that ref.
#   3. A banner is prepended saying so.
#
# Nothing else is touched, so the job bodies - the part worth keeping identical -
# are identical.
#
# USAGE
#   python3 tools/mirror_ci.py --out <dir>
# writes <dir>/.github/workflows/{build,heavy,linux-engine}.yml. Use --check to
# exit non-zero if the directory is out of date instead of writing it.

import argparse
import pathlib
import sys

SOURCE_REPOSITORY = "sheltonsilas/Madeira"
SOURCE_REF = "feature/two-variants-browser-and-linux"

BANNER = """# SPDX-License-Identifier: GPL-3.0-or-later
# Madeira Converter Exception: see LICENSE-EXCEPTION.md
#
# GENERATED FILE - DO NOT EDIT HERE. Generated by tools/mirror_ci.py from
# {source}/.github/workflows/{name}.
#
# This is the build host copy. GitHub has Actions disabled on the Madeira fork
# itself, so the builds run here and check {source}
# out by name. The job bodies below are byte-identical to the original; the only
# differences are this banner, a workflow_dispatch-only trigger with a
# `source_ref` input, and `actions/checkout` pinned to the source repository.
#
"""

CHECKOUT_PLAIN = "      - uses: actions/checkout@v4\n"

# A step with no `with:` block of its own: the line, then a blank line. This is
# the form in verify-jit-invariants and publish. Matching the blank line as well
# is what keeps this from also matching the two steps that do open a `with:`.
CHECKOUT_BARE = CHECKOUT_PLAIN + "\n"

# The two checkout steps that already carry a `with:` block, matched exactly so
# the generated file has one `with:` key per step and not two. The comments
# inside heavy.yml's are part of the block on purpose: they explain why the
# submodules are off, and that reasoning travels with the mirror.
CHECKOUT_BUILD = (
    "      - uses: actions/checkout@v4\n"
    "        with:\n"
    "          submodules: recursive\n"
    "          fetch-depth: 0\n"
)

CHECKOUT_HEAVY = (
    "      - uses: actions/checkout@v4\n"
    "        with:\n"
    "          # The LLVM source is a release tarball, not a submodule, so the\n"
    "          # submodules are dead weight here and cost several minutes.\n"
    "          submodules: false\n"
    "          fetch-depth: 1\n"
)


CHECKOUT_HEAVY_BODY = (
    "          # The LLVM source is a release tarball, not a submodule, so the\n"
    "          # submodules are dead weight here and cost several minutes.\n"
    "          submodules: false\n"
    "          fetch-depth: 1\n"
)


def pin(repository_indent, ref_indent, rest):
    return (
        "      - uses: actions/checkout@v4\n"
        "        with:\n"
        f"{repository_indent}repository: {SOURCE_REPOSITORY}\n"
        f"{ref_indent}ref: ${{{{ inputs.source_ref }}}}\n"
        + rest
    )

# The `inputs:` entries sit six spaces in: `on:` at column 0, `workflow_dispatch:`
# at two, `inputs:` at four, its entries at six. Getting this wrong is a YAML
# parse error, not a subtle one, but it is worth stating because the generated
# file is the only place the indentation is not obvious.
INPUT_INDENT = "      "


def source_input(indent=INPUT_INDENT):
    return (
        f"{indent}source_ref:\n"
        f"{indent}  description: \"Branch of {SOURCE_REPOSITORY} to build\"\n"
        f"{indent}  type: string\n"
        f"{indent}  default: \"{SOURCE_REF}\"\n"
    )


def mirror_build(text):
    """build.yml -> build host build.yml."""
    # 1. trigger
    original_trigger = (
        "on:\n"
        "  push:\n"
        '    branches: ["**"]\n'
        "  pull_request:\n"
        "  workflow_dispatch:\n"
        "    inputs:\n"
    )
    assert original_trigger in text, "build.yml: the `on:` block moved; re-read it"
    text = text.replace(
        original_trigger,
        "on:\n"
        "  workflow_dispatch:\n"
        "    inputs:\n" + source_input(),
        1,
    )

    # 2. the two bare checkouts: verify-jit-invariants and publish. Counted
    #    before either is rewritten, because a pinned checkout still contains
    #    the line being counted.
    assert text.count(CHECKOUT_BARE) == 2, (
        "build.yml: expected two bare checkouts (verify and publish), found "
        f"{text.count(CHECKOUT_BARE)}"
    )
    text = text.replace(CHECKOUT_BARE, pin("          ", "          ", "") + "\n")

    # 3. the build job's checkout, which already has a `with:` block
    assert text.count(CHECKOUT_BUILD) == 1, "build.yml: the build job's checkout moved"
    text = text.replace(CHECKOUT_BUILD, pin("          ", "          ", CHECKOUT_BUILD[len(CHECKOUT_PLAIN) + len("        with:\n"):]), 1)
    return text


def mirror_heavy(text):
    """heavy.yml -> build host heavy.yml."""
    assert "on:\n  workflow_dispatch:\n" in text, "heavy.yml: the `on:` block moved"
    text = text.replace(
        "on:\n  workflow_dispatch:\n",
        "on:\n  workflow_dispatch:\n    inputs:\n" + source_input(),
        1,
    )

    assert CHECKOUT_HEAVY in text, "heavy.yml: the checkout moved"
    text = text.replace(
        CHECKOUT_HEAVY,
        pin("          ", "          ", CHECKOUT_HEAVY_BODY),
        1,
    )
    return text


def mirror_typecheck(text):
    """swift-typecheck.yml -> build host swift-typecheck.yml.

    One job, one checkout, no inputs of its own. The push trigger goes: a push
    to a repository that never contains the source cannot mean anything.
    """
    original_trigger = (
        "on:\n"
        "  workflow_dispatch:\n"
        '  push:\n'
        '    paths: ["app/**/*.swift"]\n'
    )
    assert original_trigger in text, "swift-typecheck.yml: the `on:` block moved; re-read it"
    text = text.replace(
        original_trigger,
        "on:\n  workflow_dispatch:\n    inputs:\n" + source_input(),
        1,
    )

    assert text.count(CHECKOUT_BARE) == 1, (
        "swift-typecheck.yml: expected one bare checkout, found "
        f"{text.count(CHECKOUT_BARE)}"
    )
    text = text.replace(CHECKOUT_BARE, pin("          ", "          ", "") + "\n")
    return text


def mirror_linux_engine(text):
    """linux-engine.yml -> build host linux-engine.yml.

    It clones utmapp/UTM and never reads the Madeira source, so it needs no
    checkout change. It is mirrored anyway so the build host has one workflow
    per thing it builds, and so a reader of either repository sees the same set.
    """
    return text


MIRRORS = {
    "build.yml": mirror_build,
    "heavy.yml": mirror_heavy,
    "linux-engine.yml": mirror_linux_engine,
    "swift-typecheck.yml": mirror_typecheck,
}


def build_all(repo_root: pathlib.Path):
    out = {}
    for name, transform in MIRRORS.items():
        source = repo_root / ".github" / "workflows" / name
        text = source.read_text(encoding="utf-8")
        # Drop the original's leading SPDX/licence pair: the banner re-states it,
        # and a file with two licence headers reads like a mistake.
        lines = text.splitlines(keepends=True)
        if lines and lines[0].startswith("# SPDX-License-Identifier"):
            drop = 0
            while drop < len(lines) and lines[drop].startswith("#"):
                drop += 1
            lines = lines[drop:]
            while lines and lines[0].strip() == "":
                lines.pop(0)
            text = "".join(lines)
        mirrored = transform(text)
        out[name] = BANNER.format(source=SOURCE_REPOSITORY, name=name) + mirrored
    return out


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", help="directory to write .github/workflows into")
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if the directory does not already match; write nothing",
    )
    parser.add_argument(
        "--print",
        dest="print_one",
        metavar="NAME",
        help="print one generated workflow to stdout",
    )
    args = parser.parse_args()

    repo_root = pathlib.Path(__file__).resolve().parent.parent
    generated = build_all(repo_root)

    if args.print_one:
        sys.stdout.write(generated[args.print_one])
        return 0

    if args.check:
        target = pathlib.Path(args.out or ".") / ".github" / "workflows"
        stale = [
            name
            for name, body in generated.items()
            if not (target / name).is_file()
            or (target / name).read_text(encoding="utf-8") != body
        ]
        for name in stale:
            print(f"stale: {target / name}")
        return 1 if stale else 0

    if not args.out:
        parser.error("--out is required unless --check or --print is used")

    target = pathlib.Path(args.out) / ".github" / "workflows"
    target.mkdir(parents=True, exist_ok=True)
    for name, body in generated.items():
        path = target / name
        path.write_text(body, encoding="utf-8", newline="\n")
        print(f"wrote {path} ({len(body)} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
