#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
# Madeira Converter Exception: see LICENSE-EXCEPTION.md
#
# push_mirror.py - publish the build host workflows and, optionally, run one.
#
# The companion to tools/mirror_ci.py. That script writes the build host's
# copies of the workflows to a directory; this one sends them to the build host
# repository through the contents API, so a workflow fix can be applied without
# a checkout of a repository that exists only to have somewhere to run.
#
# The token is read from a file outside the repository and is never printed.
# Its path defaults to ~/.madeira_push_token, which is also where the repository
# push credential lives.
#
# USAGE
#   python3 tools/push_mirror.py                       # push all three
#   python3 tools/push_mirror.py heavy.yml             # push one
#   python3 tools/push_mirror.py --run heavy.yml       # push, then dispatch
#   python3 tools/push_mirror.py --runs                # show recent runs

import argparse
import base64
import json
import pathlib
import sys
import urllib.error
import urllib.request

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
import mirror_ci  # noqa: E402

BUILD_HOST = "sheltonsilas/madeira-ci"
API = "https://api.github.com"


def token(path):
    text = pathlib.Path(path).expanduser().read_text(encoding="utf-8").strip()
    if not text:
        raise SystemExit(f"{path} is empty")
    return text


def call(method, url, tok, payload=None):
    data = json.dumps(payload).encode() if payload is not None else None
    request = urllib.request.Request(
        url,
        data=data,
        headers={
            "Authorization": "token " + tok,
            "Accept": "application/vnd.github+json",
            "User-Agent": "madeira-build-host",
        },
        method=method,
    )
    try:
        with urllib.request.urlopen(request) as response:
            return response.status, json.loads(response.read() or b"null")
    except urllib.error.HTTPError as error:
        return error.code, error.read().decode(errors="replace")


def existing_sha(tok, repo, path):
    status, body = call("GET", f"{API}/repos/{repo}/contents/{path}", tok)
    if status == 200 and isinstance(body, dict):
        return body.get("sha")
    return None


def push(tok, name, body):
    path = f".github/workflows/{name}"
    payload = {
        "message": f"ci: {name}, generated by tools/mirror_ci.py",
        "content": base64.b64encode(body.encode("utf-8")).decode(),
        "branch": "main",
    }
    sha = existing_sha(tok, BUILD_HOST, path)
    if sha:
        payload["sha"] = sha
    status, reply = call("PUT", f"{API}/repos/{BUILD_HOST}/contents/{path}", tok, payload)
    if status in (200, 201) and isinstance(reply, dict):
        action = "updated" if sha else "created"
        print(f"{name}: {action} at {reply['commit']['sha'][:7]} ({len(body)} bytes)")
        return True
    print(f"{name}: FAILED {status} {str(reply)[:400]}")
    return False


def show_runs(tok, limit=6):
    status, body = call("GET", f"{API}/repos/{BUILD_HOST}/actions/runs?per_page={limit}", tok)
    if status != 200:
        print("could not read runs:", status, str(body)[:200])
        return
    for run in body.get("workflow_runs", []):
        inputs = run.get("inputs") or {}
        print(
            f"{run['id']} {run['name']:<14} {run['status']:<12} {run.get('conclusion')} "
            f"{run['head_sha'][:7]} {run['created_at']} {inputs}"
        )


def dispatch(tok, workflow, inputs):
    status, body = call(
        "POST",
        f"{API}/repos/{BUILD_HOST}/actions/workflows/{workflow}/dispatches",
        tok,
        {"ref": "main", "inputs": inputs},
    )
    if status == 204:
        print(f"{workflow}: dispatched {inputs}")
        return True
    print(f"{workflow}: dispatch FAILED {status} {str(body)[:400]}")
    return False


RUN_INPUTS = {
    "build.yml": {"source_ref": mirror_ci.SOURCE_REF},
    "heavy.yml": {"source_ref": mirror_ci.SOURCE_REF},
    "linux-engine.yml": {"targets": "interpreter-only"},
    "swift-typecheck.yml": {"source_ref": mirror_ci.SOURCE_REF},
}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("workflows", nargs="*", help="workflow file names; default all")
    parser.add_argument("--token-file", default="~/.madeira_push_token")
    parser.add_argument("--run", action="store_true", help="dispatch after pushing")
    parser.add_argument("--runs", action="store_true", help="list recent runs and exit")
    parser.add_argument("--only-run", metavar="NAME", help="dispatch without pushing")
    args = parser.parse_args()

    tok = token(args.token_file)

    if args.runs:
        show_runs(tok)
        return 0

    repo_root = pathlib.Path(__file__).resolve().parent.parent
    generated = mirror_ci.build_all(repo_root)

    if args.only_run:
        return 0 if dispatch(tok, args.only_run, RUN_INPUTS[args.only_run]) else 1

    names = args.workflows or list(generated)
    ok = True
    for name in names:
        if name not in generated:
            raise SystemExit(f"unknown workflow {name}; known: {sorted(generated)}")
        ok = push(tok, name, generated[name]) and ok
        if args.run and ok:
            ok = dispatch(tok, name, RUN_INPUTS[name]) and ok
    if ok and args.run:
        show_runs(tok)
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
